name: "PlayerManager"
description: "A plugin that allows player to manage players and acquire players information!"
version: 1.0.0
main: mukeenanyafiq\PlayerManager\Main
api: 5.0.0
author: "mukeenanyafiq"
commands:
  plmanager:
    description: "Opens a PlayerManager form"
    usage: "/plmanager or /plmanager info <player>"
    permission: playermanager.command.plmanager

permissions:
  playermanager.command.plmanager:
    default: op
    description: "Allows player to open PlayerManager form"