name: "PlayerManager"
description: "A plugin that allows players to obtain player's data and also managing a player!"
version: 1.0.0
main: mukeenanyafiq\PlayerManager\Main
api: 5.0.0
author: "mukeenanyafiq"
commands:
  plmanager:
    description: "Opens a PlayerManager form"
    usage: "/plmanager or /plmanager info <player>"
    permission: playermanager.command.plmanager

permissions:
  playermanager.command.plmanager:
    default: op
    description: "Allows user/player to open PlayerManager form"