---
# Configuration file for PlayerManager plugin

# "firstplace" - Show player's specific information in the first place
# Types:
# "model" - Shows the player's phone model (Default)
# "os" - Shows the player's device operating system
# "ip" - Shows the player's IP address
# "port" - Shows the player's port
# "ping" - Shows the player's ping
# "ui" - Shows the player's UI profile
# "gui" - Shows the player's GUI scale
# "controls" - Shows the player's control
# "uuid" - Shows the player's UUID (Unique ID)
# "health" - Shows the player's health
# "position" - Shows the player's position
# "gamemode" - Shows the player's gamemode

# Support case insensitive
# Anything inputted other than the list on the top will be set to 'model' by default.
firstplace: model

# "blacklist" - List of players that won't be able to access PlayerManager form
# Put the player's username in the list to blacklist them
blacklist: []
...