---
# Configuration file for PlayerManager plugin

# "firstplace" - Show player's specific information in the first place
# Types:
# "model" - Shows the player's phone model
# "os" - Shows the player's device operating system
# "ip" - Shows the player's IP address
# "port" - Shows the player's port
# "ping" - Shows the player's ping
# "ui" - Shows the player's UI profile
# "gui" - Shows the player's GUI scale
# "controls" - Shows the player's control
# "uuid" - Shows the player's UUID (Unique ID) (which is some long character that minecraft assign the player so that their username doesnt matter)
# "health" - Shows the player's health
# "position" - Shows the player's position
# "gamemode" - Shows the player's gamemode

# Support case insensitive so even if you're still inputting the type with some upper case words, it would still work. (ex: "Model", "oS")
# Anything inputted other than the list on the top will be set to 'model' by default.
firstplace: model

# "blacklist" - List of players that won't be able to access PlayerManager form
# Put the player's username in the list to blacklist them
blacklist: []

# "language" - Sets the plugin's language
# This also applicable to everyone, meaning the language of the form for everyone will be set to the inputted language.

# Supported language:
# "eng" - English
language: eng
...